tasks:
  - init: npm install
    command: npm run start

vscode:
  extensions:
    - esbenp.prettier-vscode@5.1.3:t532ajsImUSrA9N8Bd7jQw==
    - dracula-theme.theme-dracula@2.22.1:acEEGtphPo3sp9+wXQiSyw==
